sculpin:
    site:
        url: http://srcmvn.com
        title: Source Maven
        subtitle: Code Partition for Beau Simensen
        author: Beau Simensen
        disqus_short_name: srcmvn
        google_analytics_tracking_id: UA-12685022-2
        hub_url: http://dflydev.superfeedr.com/
sculpin_posts:
    permalink: blog/:year/:month/:day/:filename/
